steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--pack=builder=gcr.io/buildpacks/builder:google-22,env=GOOGLE_NODEJS_VERSION=18.x.x,image=us-central1-docker.pkg.dev/bcs-ha-modelexec-np/autoscaler/poller', './poller']
